//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lagerverwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auftrag
    {
        public string Jahr { get; set; }
        public int AuftragNummer { get; set; }
        public string PL { get; set; }
        public Nullable<int> BauvorhabenNr { get; set; }
        public Nullable<int> AuftraggeberNr { get; set; }
        public string Arbeitsart { get; set; }
        public Nullable<int> SR { get; set; }
        public Nullable<int> SZ { get; set; }
        public Nullable<int> NK { get; set; }
    
        public virtual Auftraggeber Auftraggeber { get; set; }
        public virtual Bauvorhaben Bauvorhaben { get; set; }
    }
}
