//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lagerverwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auftraggeber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auftraggeber()
        {
            this.Auftrag = new HashSet<Auftrag>();
        }
    
        public int AuftraggeberNr { get; set; }
        public string AuftraggeberName { get; set; }
        public string PLZ { get; set; }
        public string Ort { get; set; }
        public string Strasse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auftrag> Auftrag { get; set; }
    }
}
